apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend-ns
data:
  VITE_AUTH_API_URL: "http://auth-service.auth-ns.svc.cluster.local:8001"
  VITE_DOCS_API_URL: "http://docs-service.docs-ns.svc.cluster.local:8000"
  VITE_ANALYSIS_API_URL: "http://analysis-service.analysis-ns.svc.cluster.local:4000"